"""user role

Revision ID: 57a9492ba1a9
Revises: 4e43904abf52
Create Date: 2025-12-17 23:12:14.869413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a9492ba1a9'
down_revision: Union[str, None] = '4e43904abf52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_order_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'order_id')
    op.add_column('users', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.add_column('products', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_order_id_fkey', 'products', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
