"""orders

Revision ID: 8e3931b192a4
Revises: 6267de551199
Create Date: 2025-12-20 18:45:08.048496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3931b192a4'
down_revision: Union[str, None] = '6267de551199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('courier_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('cook_id', sa.Integer(), nullable=True))
    op.alter_column('orders', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(op.f('orders_cook_id_fkey'), 'orders', 'users', ['cook_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('orders_courier_id_fkey'), 'orders', 'users', ['courier_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_courier_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_cook_id_fkey'), 'orders', type_='foreignkey')
    op.alter_column('orders', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('orders', 'cook_id')
    op.drop_column('orders', 'courier_id')
    # ### end Alembic commands ###
