"""empty message

Revision ID: 132af46ea798
Revises: 2397245debc4
Create Date: 2025-12-25 19:07:31.839805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '132af46ea798'
down_revision: Union[str, None] = '2397245debc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_products', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_products', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_products', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_products', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
