"""remove superuser

Revision ID: bef153c9b2ae
Revises: 6267de551199
Create Date: 2025-12-18 20:01:17.486919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef153c9b2ae'
down_revision: Union[str, None] = '6267de551199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=False)
    op.drop_column('users', 'is_super_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_super_user', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('users', 'role',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
